### ISSUE TITLE
gi.repository.GLib.Error: gst_parse_error: no element "udpsrc" (1)

### ISSUE THREAD

**Issue by aradhyamathur** [bozkurthan/PX4-Gazebo-Opencv#2]
Upon trying out the method proposed I received the following error. Can you please guide ?  
Setup : Python 3.7.11, gi version 3.40.1
```
Traceback (most recent call last):
  File "lander.py", line 392, in <module>
    video = Video()
  File "lander.py", line 182, in __init__
    self.run()
  File "lander.py", line 251, in run
    self.video_sink_conf
  File "lander.py", line 205, in start_gst
    self.video_pipe = Gst.parse_launch(command)
gi.repository.GLib.Error: gst_parse_error: no element "udpsrc" (1)
```

Though I was able to capture the stream correctly in gst-launch using  ```gst-launch-1.0  -v udpsrc port=5600 caps='application/x-rtp, media=(string)video, clock-rate=(int)90000, encoding-name=(string)H264' \
! rtph264depay ! avdec_h264 ! videoconvert ! autovideosink fps-update-interval=1000 sync=false```

**Comment by julianoes** [comment]
Looking at [stackoverflow](https://stackoverflow.com/questions/57931304/gst-launch-bogus-no-element-udpsrc-error) could it be something of `gst-launch-1.0` vs `gst-launch`? Is it somehow using the wrong libs?

What are the steps to reproduce this?

**Comment by bozkurthan** [comment]
I suspect same situation. I am busy nowadays for my thesis till 19 Jan. Could you please provide more information.  Which OS do you using?
Also, I suggest to review stackoverflow page that shared by @julianoes. Maybe the version of the gstreamer version creates conflict.

**Comment by aradhyamathur** [comment]
I do not face the issue with gst-launch actually, I am able to correctly view the stream via gst-launch. The issue arises only in python interface it seems. The OS I am using is Ubuntu 20.04.

**Comment by aradhyamathur** [comment]
Hi, @bozkurthan were you able to check this further ?

**Comment by bozkurthan** [comment]
I am planning to dig into problem in this weekend. Sorry, I have busy schedule nowadays. I also suggest that look for Gstreamer library documentation to overcome this issue.

**Comment by zitongbai** [comment]
I encountered the same problem. My gstreamer is used in conda env, and the problem is resolved by install it in conda:
```bash
conda install -c conda-forge gstreamer gst-plugins-base gst-plugins-good gst-plugins-bad gst-plugins-ugly gst-libav
```
